---
- name: "update apt package."
  become: yes
  apt:
    update-cache: yes

- name: "upgrade apt package."
  become: yes
  apt:
    upgrade: "yes"

- name: "Install Docker"
  shell: |
    sudo apt-get install docker.io -y

- name: "Install MiniKube"
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    sudo install minikube-linux-amd64 /usr/local/bin/minikube
