---
- name: "Copy deployments and services files"
  copy:
    src: files/
    dest: ~/

- name: Extract config.tar.gz
  ansible.builtin.unarchive:
    src: config.tar.gz
    dest: ~/

- name: "Build and Push Docker Nextjs-green Image to a Aws Repo"
  become: true
  shell: |
    chmod +x build_push_docker.sh
    ./build_push_docker.sh

- name: "Start MiniKube"
  become: true
  shell: |
    sysctl fs.protected_regular=0
    minikube start --driver=none

- name: "Deploy Nextjs Blue App"
  become: true
  shell: |
    minikube kubectl -- apply -f nextjs-d.yml
    minikube kubectl -- apply -f nextjs-s.yml

- name: "Create Nextjs Green App Container"
  become: true
  shell: |
    docker run -d --name green -p 3030:3000 public.ecr.aws/y5l2b5h6/nextjs:green
