version: 2
jobs:
  build:
    docker:
    - image: circleci/node:14.7.0
    steps:
    - run:
        name: install dependencies and build
        command: "ls\npwd\n#npm i\n#npm run build                  \n"
workflows:
  default:
    jobs:
    - build
  version: 2

# Original config.yml file:
# version: 2.1
# 
# jobs:
#   build:
#     docker:
#       - image: circleci/node:14.7.0
#     #working_directory: ~/repo      
#     steps:
#       #- checkout
#       #- restore_cache:
#       #    keys: [build]
#       - run:
#           name: install dependencies and build
#           command: |
#             ls
#             pwd
#             #npm i
#             #npm run build                  
#       #- save_cache:
#       #    paths: [node_modules]
#       #    key: build
#                 
# workflows:
#   default:
#     jobs:
#       - build