Description: >
  Nextjs EC2 stack.

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Nextjs
      GroupDescription: Allow port 22 and port 32321.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 32321
          ToPort: 32321
          CidrIp: 0.0.0.0/0

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Roles:
        - eksworkshop-admin

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.small
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20      
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      IamInstanceProfile:
          Arn: !GetAtt InstanceProfile.Arn
          Name: !GetAtt InstanceProfile.Name    
      ImageId: ami-03d5c68bab01f3496
      Tags:
        - Key: Name
          Value: Nextjs
