version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.7.0 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps-
      - run:
          name: install dependencies and build
          command: |
            yarn set version latest
            yarn install
            yarn run build                  
      - save_cache:
          key: v2-deps-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
 
  test:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps-
      - run:
          name: test build
          command: |
            yarn set version latest
            yarn run test
            
  scan:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps-{{ checksum "yarn.lock" }}
            - v2-deps-
      - run:
          name: test build
          command: |
            yarn set version latest
            yarn audit --audit-level=critical


workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - scan:
          requires: [test]               