version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.7.0
    working_directory: ~/repo      
    steps:
      - checkout
      - restore_cache:
          keys: [b-key]
      - run:
          name: install dependencies and build
          command: |
            npm i
            npm run build                  
      - save_cache:
          paths: [node_modules/]
          key: b-key
 
  test:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys: [b-key]
      - run:
          name: test build
          command: |
            ls
            npm run test
          
  scan:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys: [b-key]
      - run:
          name: test build
          command: |
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - scan:
          requires: [test]          