version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.7.0
    working_directory: ~/repo      
    steps:
      - checkout
      - restore_cache:
          keys: [build]
      - run:
          name: install dependencies and build
          command: |
            npm i
            npm run build                  
      - save_cache:
          paths: [node_modules]
          key: build
 
  test:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys: [build]
      - run:
          name: test build
          command: |
            npm i
            npm run test
          

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]