version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14.7.0 
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: install dependencies and build
          command: |
            npm i
            npm run build                  
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
 
  test:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: test build
          command: |
            npm run test
            
  scan:
    docker:
      - image: circleci/node:14.7.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "package-lock.json" }}
            - v1-deps-
      - run:
          name: test build
          command: |
            npm audit --audit-level=critical

workflows:
  default:
    jobs:
      - build
      - test:
          requires: [build]
      - scan:
          requires: [test]          